### PR TITLE
3 8 18

### PR DESCRIPTION
**Pull request by jedwardwalters**
Changes affiliation for JW, addressed other small changes in issues.

### CODE REVIEW

**Comment by jedwardwalters** [comment]
@wsalesky Did I do something wrong here? I only meant to commit my "Index and Editorial Page Corrections" over on the Hugoye-app branch, but I somehow also did a lot of your things and it brought me over to the Srophe git--I'm not sure how that happened.

**Comment by jedwardwalters** [comment]
Yes, I did something wrong. I'm going to revert this merger. Sorry! I knew I'd mess something up somehow!

**Comment by wsalesky** [comment]
@jedwardwalters I think you made the pull request on the wrong repo. Lets roll this back and try again. When you make the pull request make sure you are making it to the Hugoye fork. The first option is always the parent fork (in this case the Corpus)

**Comment by wsalesky** [comment]
@jedwardwalters let me know if you need help reverting this.

**Comment by jedwardwalters** [comment]
If you have a minute, can you do it? Now I’m nervous about making another mistake. Sorry about this!

**Comment by wsalesky** [comment]
@jedwardwalters Yes, in the future just remember to check the base fork, so you don't commit upstream. It takes a little practice but no real harm done.

**Comment by jedwardwalters** [comment]
Got it. I realized what had happened, but only after the fact. Thanks for your help.

**Comment by wsalesky** [comment]
I think we are okay now.

**Comment by jedwardwalters** [comment]
Great. I just checked and saw my changes have already showed up (in the right place this time!). Thanks.

**Pull request merged**
